/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.dictionary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class DictionaryTest {
    Dictionary dictionary;

    @BeforeEach
    // Executed before each test
    void setUp(){
        dictionary = new Dictionary();
    }

    @Test
    void testAddWordsToDictionary() throws DictionaryException{
        // Works if a) is correct
        // Add to dictionary
        dictionary.addWordsToDictionary("apple", "apfel");
        // Check if dictionary contains the added word
        assertEquals("apfel", dictionary.getDictionary().get("apple"));
    }

    @Test
    void testAddingException() throws DictionaryException {
        // Works if a) is correct
        // Add to dictionary
        dictionary.addWordsToDictionary("apple", "apfel");

        // Test if adding again throws exception
        assertThrows(DictionaryException.class ,() -> dictionary.addWordsToDictionary("apple", "apfel"));

    }
}
