/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.dictionary;

public class App {
    public static void main(String[] args) {
        System.out.println("Run tests in test classes to see if your app works.");
        System.out.println("This file can be used for manual testing purposes");
    }
}
