name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Dictionary
      id: test-dictionary
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Dictionary
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-DICTIONARY_RESULTS: "${{steps.test-dictionary.outputs.result}}"
      with:
        runners: test-dictionary
